config/routes.rb
Rails.application.routes.draw do
  # root page routes.
  get "/:locale" => 'pages#home', as: "locale_root"
  root to: "pages#home"

  # RESTful authentication router.
  devise_for :agents, path: "accounts",
             path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }

  # I18n routing.
  scope "(:locale)", locale: /en|ar/ do
    # Named static pages routes.
    get "contact" => "pages#contact"

    # REST Resources routes.
    resources :surveys do
      get  "invitation" => "surveys#invitation", on: :member
      post "invitation" => "surveys#invite", on: :member

      collection do
        get   "preview/:unique_id/" => "surveys#preview", as: "preview"
        patch "preview/:unique_id/" => "surveys#fill", as: "fill"
        get   ":unique_id/thank"    => "surveys#thank", as: "thank"
      end
    end

    # Dashboard Routes.
    scope :dashboard do
      get "main"     => "dashboard#main", as: "dashboard_main"
      get "report"   => "dashboard#report", as: "dashboard_report"
      get "stats"    => "dashboard#stats", as: "dashboard_stats"
      get "settings" => "dashboard#settings", as: "dashboard_settings"
    end
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  # Relationships

  # Attributes
  serialize :answer
  enum customer_job_title: [:mr, :mrs, :ms, :eng, :dr]

  # Validators
  validates :fmdh_agent_name, presence: true, length: { minimum: 3, maximum: 40 }
  validates :customer_name,   presence: true, length: { minimum: 3, maximum: 40 }
  validates :sr_number, presence: true, uniqueness: true,
                        numericality: { only_integer: true, greater_than: 1800, less_than: 10000 }
  validates :customer_email, presence: true, length: { minimum: 6, maximum: 200 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validates :customer_phone_number, length: { minimum: 10, maximum: 15 }, allow_blank: true
  validates :customer_job_title, presence: true
  validates :request_first_notification_date_and_time, presence: true
  validates :initial_reply_email_date_and_time, presence: true
  validates :request_resolution_date, presence: true
  validates :customer_request_summary, presence: true, length: { minimum: 8, maximum: 10000 }
  validates :unique_id, presence: true, uniqueness: true

  # Callbacks
  before_validation :generate_unique_id
  before_save :timestamp_when_filled

  # Scopes
  default_scope -> { order id: :desc }

  # Will_paginate setup
  self.per_page = 25

  # Business logic & methods
  def conceal survey_answer
    if filled? || !self[:answer].blank?
      raise ActiveRecord::ReadOnlyRecord.new 'Survey is already answered'
    else
      self[:answer] = survey_answer.attributes
      filled_in
    end
  end

  def answer
    current = read_attribute :answer
    !current.nil? ? current.with_indifferent_access : write_attribute(:answer, {})
  end

  def self.job_titles_for_select
    customer_job_titles.collect do |title, _|
      [human_job_title(title), title]
    end
  end

  def self.human_job_title job_title
    self.human_enum_name :customer_job_title, job_title
  end

  private

  def generate_unique_id
    self[:unique_id] = random_token if self[:unique_id].nil? || self[:unique_id].length < 6
  end

  def random_token
    SecureRandom.urlsafe_base64 6
  end

  def filled_in
    self[:filled] = true
  end

  def timestamp_when_filled
    self[:filled_at] = DateTime.now if filled? && self[:filled_at].nil?
    # TODO: maybe cleae :filled_at if filled is return back to false.
    # But this behavior is really unexpected and defeat the pupose of asking customers to fill.
    # Mark: Delete this comment in next revision.
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # Action filters
  skip_before_action :authenticate_agent!, only: [:preview, :fill, :thank]
  before_action :authenticate_admin!, only: [:destroy]
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :invitation, :invite]
  before_action :set_survey_by_unique_id, only: [:preview, :fill, :thank]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all.paginate(page: params[:page]).per_page records_count
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    @job_title = params[:survey][:customer_job_title]
    puts "#" * 50
    puts @job_title
    puts "#" * 50
    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey,
                      notice: t('controller.created', m: t('surveys.singular')) }

        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey,
                      notice: t('controller.updated', m: t('surveys.singular')) }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url,
                    notice: t('controller.destroyed', m: t('surveys.singular')) }
      format.json { head :no_content }
    end
  end

  # GET /surveys/preview/:unique_id
  # GET /surveys/preview/:unique_id.json
  # Shows the customer a survey in fill (write) mode.
  def preview
    set_survey_answer

    unless current_agent
      @survey.increment :hits_counter
      @survey.save
    end
  end

  # PATCH/PUT /surveys/fill
  # PATCH/PUT /surveys/fill.json
  # Persists the customer's survey fill.
  def fill
    @survey_answer = SurveyAnswer.new survey_answer_params

    respond_to do |format|
      if @survey.filled?
        flash[:info] = "Survey has already been filled."
        redirect_to(thank_surveys_url) && return
      end

      if @survey_answer.valid?
        format.html {
          conceal_and_persist
          SurveyMailer.thank_email(@survey).deliver_later
          SurveyMailer.fill_notification_email(@survey).deliver_later
          redirect_to thank_surveys_url, success: t('surveys.filled_successfully')
        }
        format.json { render :thank, status: :ok, location: @survey }
      else
        format.html { render :preview }
        format.json { render json: @survey_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /surveys/:id/invitation
  # GET /surveys/:id/invitation.json
  # Shows the customer a survey in fill (write) mode.
  def invitation
    render :invitation, :layout => 'popup'
  end

  # POST /surveys/:id/invitation
  # POST /surveys/:id/invitation.json
  # Sends the invitation email.
  def invite
    SurveyMailer.invite_email(@survey).deliver_later
    render :invite, :layout => 'popup'
  end


  # GET /surveys/:unique_id/thank
  # GET /surveys/:unique_id/thank
  # Shows customer thank-you screen after successful survey fill.
  def thank
    unless @survey.filled?
      flash[:danger] = "Survey is not filled. Please complete it before proceeding."
      redirect_to preview_surveys_url
    else
      render :thank
    end
  end

  private

  def set_survey
    @survey = Survey.find params[:id]
  end

  def set_survey_by_unique_id
    @survey = Survey.find_by! unique_id: params[:unique_id]
  end

  def set_survey_answer
    @survey_answer = @survey.filled? ? SurveyAnswer.new(@survey.answer) : SurveyAnswer.new
    @survey_answer.survey_unique_id = @survey.unique_id
    @survey_answer.sr_number = @survey.sr_number
  end

  def survey_params
    params.require(:survey).permit :fmdh_agent_name, :customer_name, :customer_phone_number,
      :sr_number, :request_first_notification_date_and_time, :initial_reply_email_date_and_time,
      :request_resolution_date, :customer_request_summary, :customer_email, :customer_job_title
  end

  def survey_answer_params
    params.require(:survey_answer).permit :q1_answer, :q2_answer, :q3_answer, :q4_answer, :q5_answer,
      :suggestions_and_notes, :unique_id
  end

  def records_count
    !params[:count].blank? ? params[:count].to_i : Survey.per_page
  end

  def conceal_and_persist
    @survey.conceal @survey_answer
    @survey.save
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def survey_breadcrumb_title survey
    "#{t 'surveys.singular'} #{t 'for'} #{t 'surveys.sr_with_no', no: survey.sr_number}"
  end

  def filled_status survey
    t survey.filled? ? '_yes' : '_no'
  end

  def filled_css_class survey
    survey.filled? ? 'blue-dark' : 'red-dark'
  end

  def preview_path survey
    preview_surveys_path @survey.unique_id
  end

  def preview_url survey
    preview_surveys_url unique_id: @survey.unique_id
  end

  def pad_when_little_records list
    return unless list.respond_to? :count

    records_pads = { 0 => 13, 1 => 11, 2 => 9, 3 => 6, 4 => 4, 5 => 2 }
    records_num = list.count

    records_pads[records_num].times { yield } if records_pads.key? records_num
  end

  def survey_form_into survey
    simple_format t('survey_questions.intro', no: survey.sr_number,
      sr_summary: survey.customer_request_summary.strip,
      sr_date: formatted_with_ago(survey.request_first_notification_date_and_time))
  end

  def get_alternative_lang format = :short
    get_t = -> (lang) { format == :long ? t("#{lang}_long") : t("#{lang}_short") }

    case I18n.locale
    when :en
      get_t.call 'arabic'
    when :ar
      get_t.call 'english'
    else
      raise Error.new 'Something went wrong.'
    end
  end

  def verify_rating_option attr
    return false if params[:survey_answer].blank?

    attr_paramed = params[:survey_answer][attr]
    attr_paramed && (1..5).include?(attr_paramed.to_i) ? true : false
  end

  def check_rating_option attr, value
    verify_rating_option(attr) && params[:survey_answer][attr].to_i == value ? true : false
  end

  def check_rating_option_for_radio attr, value
    check_rating_option(attr, value) ? "checked" : ""
  end

  def check_rating_option_in_css attr, value
    check_rating_option(attr, value) ? "active" : ""
  end

  def humanize_job_title survey
    Survey.human_job_title survey.customer_job_title
  end
end

app/views/surveys/_form.html.haml
.row
  .col-md-9
    .panel.panel-warning
      .panel-heading
        %h4= t 'surveys.record_data'
      .panel-body
        = form_for @survey, html: { role: "form", class: "form-horizontal" } do |f|
          = render "shared/error_messages", object: survey

          .form-group.field
            = f.label :fmdh_agent_name, class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :fmdh_agent_name, class: "form-control"
          .form-group.field
            = f.label :customer_name, class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :customer_name, class: "form-control"
          .form-group.field
            = f.label :customer_job_title, class: "col-sm-3 control-label"
            .col-sm-9
              = f.select :customer_job_title, options_for_select(Survey.job_titles_for_select, selected: @job_title), {}, class: "form-control"
          .form-group.field
            = f.label :customer_email, class: "col-sm-3 control-label"
            .col-sm-9
              = f.email_field :customer_email, class: "form-control"
          .form-group.field
            = f.label :customer_phone_number, class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :customer_phone_number, class: "form-control"
          .form-group.field
            = f.label :sr_number, class: "col-sm-3 control-label"
            .col-sm-9
              = f.number_field :sr_number, class: "form-control"
          .form-group.field
            = f.label :request_first_notification_date_and_time, class: "col-sm-3 control-label"
            .col-sm-9
              = f.datetime_select :request_first_notification_date_and_time, {}, class: ""
          .form-group.field
            = f.label :initial_reply_email_date_and_time, class: "col-sm-3 control-label"
            .col-sm-9
              = f.datetime_select :initial_reply_email_date_and_time, {}, class: ""
          .form-group.field
            = f.label :request_resolution_date, class: "col-sm-3 control-label"
            .col-sm-9
              = f.datetime_select :request_resolution_date, {}, class: ""
          .form-group.field
            = f.label :customer_request_summary, class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_area :customer_request_summary, class: "form-control"
          .actions.btn-toolbar
            .pull-left.flip
              = render 'shared/back_button'
            = f.button type: 'submit', class: "btn btn-success btn-striped center-block pull-right flip" do
              %i.glyphicon.glyphicon.glyphicon-ok.green-secondary
              %span.green-dark
                &nbsp;
                = form_submit_button_text survey

  .col-md-3
    = render 'unique_id_widget'

app/views/surveys/_survey_answer.html.haml
- if @survey.filled?
  %hr.green
  .row
    %p.col-sm-3.strong= Survey.human_attribute_name 'answer'
    .col-sm-9
      - (1..5).each do |num|
        - q = "q#{num}_answer".to_sym
        .row
          %p.col-sm-6.strong= SurveyAnswer.human_attribute_name q
          %p.col-sm-6.info
            %strong= @survey.answer[q]
      .row
        %p.col-sm-6.strong= SurveyAnswer.human_attribute_name 'suggestions_and_notes'
        %p.col-sm-6.info= @survey.answer[:suggestions_and_notes]

app/views/surveys/_survey_form.html.haml
.row
  .col-sm-12
    .material-form
      .panel.panel-green
        .panel-heading
          %h4= t 'surveys.customer_survey'
        .panel-body
          = form_for survey_answer, url: fill_surveys_path, method: :patch,
                     html: { role: "form", class: "form-horizontal" } do |f|
            = render "shared/generic_error_message", object: survey_answer
            - (1..5).each do |num|
              - q_attr = "q#{num}_answer".to_sym
              .form-group.field
                = f.label q_attr,
                  t("survey_questions.q#{num}", no: survey_answer.sr_number),
                  class: "col-sm-5 control-label"
                .col-sm-7
                  = render "survey_rating_options", f: f, attr_name: q_attr
                  - if survey_answer.errors.messages[q_attr].any?
                    %p.center.red-dark
                      %em= survey_answer.errors.messages[q_attr].first
            .form-group.field
              = f.label :suggestions_and_notes, t('survey_questions.suggestions_and_notes'),
                          class: "col-sm-5 control-label"
              .col-sm-7
                = f.text_area :suggestions_and_notes, class: "form-control", rows: 4
                = hidden_field_tag :unique_id, survey_answer.survey_unique_id
            .row
              .col-sm-7.col-sm-push-5.actions
                %br
                .center
                  = f.button type: 'submit', class: "btn btn-success btn-outline btn-circle" do
                    %i.glyphicon.glyphicon.glyphicon-send.green-primary
                    %span.green-dark
                      &nbsp;
                      = t 'forms.submit'

app/views/surveys/_survey_other_lang_alert.html.haml
.alert.alert-warning.alert-striped-left.alert-dismissible{ role: "alert" }
  %button{ type: "button", class: "close", "data-dismiss": "alert", "aria-label": "Close" }
    %span{ "aria-hidden": "true" }
      &times;
  - unless survey.filled?
    %p= t 'surveys.available_in_other_lang', lang: get_alternative_lang
  - else
    %p= t 'surveys.available_in_other_lang_for_review_only', lang: get_alternative_lang
  %p.survey-lang-notice.center
    - unless survey.filled?
      = link_to t('surveys.available_in_other_lang_button', lang: get_alternative_lang(:long)),
                url_for(locale: other_locale), class: "btn btn-warning btn-striped"
    - else
      = link_to t('surveys.available_in_other_lang_for_review_only_button',
                lang: get_alternative_lang(:long)), url_for(locale: other_locale),
                class: "btn btn-warning btn-striped"

app/views/surveys/index.html.haml
- provide :title, t('surveys.all')

.row
  .col-sm-12
    %nav
      %ul.breadcrumb
        %li= link_to t('home'), root_path
        %li= link_to t('surveys.plural'), surveys_path

    %header.bg-lightgray
      .row
        .col-md-8
          %h2.listing-title= t 'surveys.listing'

        .col-md-4
          = link_to new_survey_path, class: 'btn btn-primary btn-striped pull-right flip' do
            %i.glyphicon.glyphicon.glyphicon-plus
            &nbsp;
            = t 'forms.new'
      %hr

    %section
      .table-responsive
        %table.table.table-hover.table-bordered
          %thead
            %tr.success
              %th= Survey.human_attribute_name 'id'
              %th= Survey.human_attribute_name 'fmdh_agent_name'
              %th= Survey.human_attribute_name 'customer_name'
              %th= t 'surveys.sr_number_short'
              %th= Survey.human_attribute_name 'request_resolution_date'
              %th= Survey.human_attribute_name 'filled'
              %th= Survey.human_attribute_name 'filled_at'
              %th
                %i.glyphicon.glyphicon-cog

          %tbody
            - @surveys.each do |survey|
              %tr
                %td
                  %strong= link_to survey.id, survey
                %td= survey.fmdh_agent_name
                %td= survey.customer_name
                %td
                  %em= survey.sr_number
                %td= formatted_short_date survey.request_resolution_date
                %td{ class: filled_css_class(survey) }= filled_status survey
                %td= formatted_ago(survey.filled_at) || t('not_yet')
                %td
                  .listing-btn-toolbar
                    = link_to survey, class: 'btn btn-default btn-sm', title: t('forms.show'),
                              "data-toggle" => "tooltip", "data-placement" => "bottom" do
                      %i.glyphicon.glyphicon-list-alt
                    = link_to edit_survey_path(survey), class: 'btn btn-primary btn-sm',
                              title: t('forms.edit'), "data-toggle" => "tooltip",
                              "data-placement" => "bottom" do
                      %i.glyphicon.glyphicon-edit
                    = link_to survey, :method => :delete, class: "btn btn-sm btn-danger",
                              title: t('forms.delete'), data: { confirm: t('forms.confirm_delete'), disable_with: t('forms.disable_with_delete') },
                              "data-toggle" => "tooltip", "data-placement" => "bottom" do
                      %i.glyphicon.glyphicon-trash
      %br
      .center
        = will_paginate @surveys, renderer: BootstrapPagination::Rails
        %h5.gray-light.right= page_entries_info @surveys

    - pad_when_little_records @surveys do
      %br.hidden-xs

app/views/surveys/invitation.html.haml
.mailing
  .row
  .col-sm-12
    .row
      .col-sm-2
        %p
          %strong= t 'forms.to'
      .col-sm-10
        %p#invitation-to.inline= mail_to @survey.customer_email, nil, class: 'underline'
        .pull-right.flip.inline= render "shared/copy_button", el_target: "#invitation-to"
    .row
      .col-sm-2
        %p
          %strong= t 'forms.subject'
      .col-sm-10
        %p#invitation-subject.inline= t 'survey_emails.invitation.subject', sr_number: @survey.sr_number
        .pull-right.flip.inline= render "shared/copy_button", el_target: "#invitation-subject"
    .row
      .col-sm-2
        %p
          %strong= t 'forms.message'
      .col-sm-10
    .row
      .col-sm-12
        #invitation-msg
          = simple_format t('survey_emails.invitation.text_html',
              sr_number: @survey.sr_number,
              summary: @survey.customer_request_summary.strip, customer_name: @survey.customer_name,
              time_ago: formatted_ago(@survey.initial_reply_email_date_and_time),
              job_title: humanize_job_title(@survey), greeting: greeting_phrase,
              link: preview_url(@survey))

        = render 'shared/mailer_signature'

    .row
      .col-sm-12
        .center
          = render "shared/copy_button", el_target: "#invitation-msg"
          = link_to invitation_survey_path, method: :post, data: { confirm: t('generic_confirm_msg'),
                    disable_with: t('forms.disable_with_sending') },
                    class: "btn btn-danger btn-sm btn-circle btn-outline margin" do
            %i.fa.fa-paper-plane-o.text-danger
            &nbsp;
            %span.text-danger= t('forms.send')

        %br

app/views/surveys/new.html.haml
- provide :title, t('surveys.new')

.row
  .col-sm-12
    %nav
      %ul.breadcrumb
        %li= link_to t('home'), root_path
        %li= link_to t('surveys.plural'), surveys_path
        %li.active= t 'forms.new'

    %header.bg-lightgray
      .row
        .col-md-10
          %h2.listing-title= t 'surveys.new'
      %hr

= render 'form', survey: @survey

app/views/surveys/preview.html.haml
- provide :title, t('surveys.preview_with_sr_title', no: @survey.sr_number)

.row
  .col-sm-12
    = render 'survey_other_lang_alert', survey: @survey
    %header.bg-lightgray
      .row
        .col-md-8
          %h2.listing-title
            = t 'surveys.survey_sr_title', no: @survey.sr_number
      %hr
      - if agent_signed_in?
        %p.pull-right.flip
          = "#{t 'surveys.clicked_counter'}: "
          = @survey.hits_counter
          &nbsp;
          = button_tag type: 'button', class: "btn btn-default btn-sm",
                      "data-toggle" => "tooltip", "data-placement" => "top",
                      title: t('surveys.clicked_counter_note') do
            %i.fa.fa-info

.row
  .col-sm-12
    / Nav tabs
    %ul.nav.nav-tabs{ role: "tablist" }
      %li{ role: "presentation", class: "#{"active" unless @survey.filled?}" }
        %a{ href: "#survey-fill", 'aria-controls': "home", role: "tab", data: { toggle: 'tab',
            turbolinks: 'false' } }
          = t 'surveys.singular'
      %li{ role: "presentation" }
        %a{ href: "#survey-details", 'aria-controls' => "home", role: "tab",
            data: { toggle: 'tab', turbolinks: 'false' } }
          = t 'surveys.sr_info'
      - if @survey.filled?
        %li.active{ role: "presentation" }
          %a{ href: "#survey-thank", 'aria-controls': "home", role: "tab", data: { toggle: 'tab',
              turbolinks: 'false' } }
            = t 'surveys.thank_you'

    / Tab panes
    .tab-content
      %div{ role: "tabpanel", class: "tab-pane #{"active" unless @survey.filled?}", id: "survey-fill" }
        %section.survey-info
        - unless @survey.filled?
          .callout.callout-info
            %p= t 'survey_questions.heading', name: @survey.customer_name,
                  job_title: humanize_job_title(@survey)
            = survey_form_into @survey
          %section.survey-for-fill
            = render 'survey_form', survey_answer: @survey_answer
        - else
          %section.survey-for-fill
            = render 'survey_view_only', survey_answer: @survey_answer

      %div{ role: "tabpanel", class: "tab-pane", id: "survey-details" }
        %section.col-md-11.col-md-push-1
          .record-details.survey-info
            = render "survey_case_info", survey: @survey

      - if @survey.filled?
        %div{ role: "tabpanel", class: "tab-pane active", id: "survey-thank" }
          = render 'survey_thank_message', survey: @survey

app/views/surveys/show.html.haml
- provide :title, t('surveys.showing')

.row
  .col-sm-12
    %nav
      %ul.breadcrumb
        %li= link_to t('home'), root_path
        %li= link_to t('surveys.plural'), surveys_path
        %li.active= t 'details'

    %header.bg-lightgray
      .row
        .col-md-8
          %h2.listing-title
            - if I18n.locale == :ar
              = t 'details'
            = t 'surveys.survey_sr_title', no: @survey.sr_number
            - if I18n.locale == :en
              = t 'details'
      %hr

.row
  %section.col-md-10.col-md-push-1.col-sm-12.record-details
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'fmdh_agent_name'
      %p.col-sm-6.info= @survey.fmdh_agent_name
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'customer_name'
      %p.col-sm-6.info= @survey.customer_name
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'customer_job_title'
      %p.col-sm-6.info= Survey.human_job_title @survey.customer_job_title
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'customer_email'
      %p.col-sm-6.info= mail_to @survey.customer_email, nil, class: 'underline'
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'customer_phone_number'
      %p.col-sm-6.info= @survey.customer_phone_number
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'sr_number'
      %p.col-sm-6.info= @survey.sr_number
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'request_first_notification_date_and_time'
      %p.col-sm-6.info= formatted @survey.request_first_notification_date_and_time
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'initial_reply_email_date_and_time'
      %p.col-sm-6.info= formatted @survey.initial_reply_email_date_and_time
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'request_resolution_date'
      %p.col-sm-6.info= formatted @survey.request_resolution_date
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'customer_request_summary'
      %p.col-sm-6.info= @survey.customer_request_summary
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'unique_id'
      %p.col-sm-6.info.strong= @survey.unique_id
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'filled'
      %p.col-sm-6.info
        %em{ class: filled_css_class(@survey) }= filled_status @survey
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'filled_at'
      .col-sm-6.normalize
        .col-sm-6.info.blue-dark= formatted(@survey.filled_at)
        .col-sm-6.info.blue-dark= formatted_ago @survey.filled_at
    %hr
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'created_at'
      .col-sm-6.normalize
        .col-sm-6.info
          %em.green-darker= formatted @survey.created_at
        .col-sm-6.info
          %em.green-darker= formatted_ago @survey.created_at
    .row
      %p.col-sm-6.strong= Survey.human_attribute_name 'updated_at'
      .col-sm-6.normalize
        .col-sm-6.info
          %em.green-darker= formatted @survey.updated_at
        .col-sm-6.info
          %em.green-darker= formatted_ago @survey.updated_at

    = render 'survey_answer', survey: @survey

    %hr
    .row
      .col-md-6.pull-left.pad-down
        .btn-toolbar
          = link_to preview_path(@survey), class: "btn btn-primary", "data-toggle" => "tooltip",
                    "data-placement" => "top", title: t('surveys.preview_tooltip') do
            %i.glyphicon.glyphicon-eye-open
            &nbsp;
            = t('surveys.preview')
          = link_to "javascript:void(0)", class: "btn btn-info",
                    "data-toggle" => "tooltip", "data-placement" => "top",
                    title: t('surveys.generate_invitation_email_tooltip'),
                    "data-turbolinks" => "false", "data-popup" => "true",
                    "data-popup-link" => invitation_survey_url(@survey),
                    "data-popup-title" => t('surveys.invitation_email_window') do
            %i.glyphicon.glyphicon-envelope
            &nbsp;
            = t('surveys.generate_invitation_email')
      .col-md-6.action-buttons.pull-right
        = link_to t('back'), surveys_path, class: "btn btn-default btn-outline"
        = link_to t('forms.edit'), edit_survey_path(@survey), class: "btn btn-primary btn-outline"
        = link_to t('forms.delete'), @survey, method: :delete, class: "btn btn-danger btn-outline",
                  data: { confirm: t('forms.confirm_delete'),
                          disable_with: t('forms.disable_with_delete') }