config/routes.rb
Rails.application.routes.draw do
  # root page routes.
  get "/:locale" => 'pages#home', as: "locale_root"
  root to: "pages#home"

  # RESTful authentication router.
  devise_for :agents, path: "accounts",
             path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }

  # I18n routing.
  scope "(:locale)", locale: /en|ar/ do
    # Named static pages routes.
    get "contact" => "pages#contact"

    # REST Resources routes.
    resources :surveys do
      get  "invitation" => "surveys#invitation", on: :member
      post "invitation" => "surveys#invite", on: :member

      collection do
        get   "preview/:unique_id/" => "surveys#preview", as: "preview"
        patch "preview/:unique_id/" => "surveys#fill", as: "fill"
        get   ":unique_id/thank"    => "surveys#thank", as: "thank"
      end
    end

    # Dashboard Routes.
    scope :dashboard do
      get "main"     => "dashboard#main", as: "dashboard_main"
      get "report"   => "dashboard#report", as: "dashboard_report"
      get "stats"    => "dashboard#stats", as: "dashboard_stats"
      get "settings" => "dashboard#settings", as: "dashboard_settings"
    end
  end
end

app/views/layouts/_footer.html.haml
%footer.container-fluid.footer
  .row
    .col-sm-6
      %p.pt-sans
        &copy;
        = "#{t 'ric_fmhd'} | #{t 'customer_surveys_center'} - (#{footer_year})"
    .col-sm-6
      %ul.links.green-dark
        %li= link_to t('home'), root_path
        %li &bull;
        %li= link_to t('contact'), contact_path

app/views/layouts/_header.html.haml
%nav.navbar.navbar-green
  .container-fluid
    .navbar-header
      %button(type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false")
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: root_path }
        %span.fa.fa-check-square-o &nbsp;
        %span= t 'customer_surveys_center'

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right.flip
        - if agent_signed_in?
          %li.dropdown.center
            %a#account-icon.dropdown-toggle{ href: "#", data: { toggle: "dropdown" }, role: "button",
            "aria-haspopup": "true", "aria-expanded": "false" }
              %span.glyphicon.glyphicon-object-align-bottom
              &nbsp;
              = t 'dashboard'
            %ul.dropdown-menu
              %li.center= link_to t('main'), dashboard_main_path
              %li.center= link_to t('browse_surveys'), surveys_path
              - if admin?
                %li.divider{ role: "separator" }
                %li.center= link_to t('report'), dashboard_report_path
                %li.center= link_to t('statistics'), dashboard_stats_path
                %li.center= link_to t('settings'), dashboard_settings_path
              %li.divider{ role: "separator" }
              %li.center= link_to t('logout'), destroy_agent_session_path, method: :delete,
                          data: { confirm: t('generic_confirm_msg') }

        %li.center= link_to t('arabic'), url_for(locale: :ar)
        %li.center= link_to t('English'), url_for(locale: :en)

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title yield :title
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    - if I18n.locale == :ar
      = stylesheet_link_tag 'rtl', media: 'all', 'data-turbolinks-track' => 'reload'
      = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lateef|Scheherazade&subset=arabic',
                            media: 'all', 'data-turbolinks-track' => 'reload'
      = stylesheet_link_tag 'https://fonts.googleapis.com/earlyaccess/notonaskharabicui.css',
                            media: 'all', 'data-turbolinks-track' => 'reload'

    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
    = render "layouts/shim"
  %body{ class: locale_css_class }
    .wrapper
      = render "layouts/header"

      .container
        = render "shared/flash_messages"
        = yield

      = render "layouts/footer"
      -# - if Rails.env.development?
      -#   = debug(params)

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title= page_title yield :title
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
    = render "layouts/shim"
  %body.login-view
    .container
      - flash.each do |name, msg|
        .row
          = content_tag :div, class: "callout callout-#{name}", role: 'callout' do
            = msg
      .row
        = yield

app/views/layouts/popup.html.haml
!!!
%html
  %head
    %title= page_title yield :title
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = stylesheet_link_tag 'popup', media: 'all', 'data-turbolinks-track' => 'reload'
    - if I18n.locale == :ar
      = stylesheet_link_tag 'rtl', media: 'all', 'data-turbolinks-track' => 'reload'
      = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lateef|Scheherazade&subset=arabic',
                            media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
    = render "layouts/shim"
  %body{ class: locale_css_class }
    .wrapper
      .container
        = render "shared/flash_messages"
        = yield